In [5]:
import pandas as pd

In [6]:
data = [1,2,3,4,5]
series = pd.Series(data)
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [7]:
data = {"a": 1, "b": 2, "c": 3}
series_dict = pd.Series(data)
series_dict

a    1
b    2
c    3
dtype: int64

In [9]:
dataa = {
    "Name" : ["Alice", "Bob", "Charlie"],
    "Age" : [25, 30, 35],
    "City" : ["New York", "Los Angeles", "Chicago"]
}
df = pd.DataFrame(dataa)
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [10]:
# dataframe from list of dictionaries
dataa = [
    {"Name" : "Alice","Age": 32, "City": "Charlie"},
    {"Name" : "Bob", "Age": 30, "City": "Los Angeles"},
    {"Name" : "Charlie", "Age": 35, "City": "Chicago"}
]

df = pd.DataFrame(dataa)
df

      Name  Age         City
0    Alice   32      Charlie
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [12]:
# Dataframe
data = pd.read_csv('london_weather.csv', sep = ',')
data.head(5)

,Unnamed: 0,Date,Max.TemperatureC,Min.TemperatureC,Max.Gust.SpeedKPH,Events,Season
0,1,1996-06-30,NaN,NaN,NaN,NaN,Summer
1,2,1996-07-01,19.0,11.0,28.0,Rain,Summer
2,3,1996-07-02,20.0,10.0,NaN,NaN,Summer
3,4,1996-07-03,19.0,12.0,NaN,Rain,Summer
4,5,1996-07-04,19.0,12.0,25.0,Rain,Summer

In [29]:
data.iat[1, 1]  # Accessing the first element

'1996-07-01'

In [15]:
# loc is for row index, iloc is for column index
df.loc[0]  # First row
 # First row

Name      Alice
Age          32
City    Charlie
Name: 0, dtype: object

In [18]:
df.loc[0][0]

C:\Users\USER\AppData\Local\Temp\ipykernel_6148\3754930180.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][0]

'Alice'

In [19]:
df

      Name  Age         City
0    Alice   32      Charlie
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [ ]:
df.at[1,'Age'] #getting row index with the colum name

np.int64(30)

In [21]:
df.iat[2,2]

'Chicago'

In [22]:
df['Salary'] = [50000, 60000, 70000]

In [23]:
df

      Name  Age         City  Salary
0    Alice   32      Charlie   50000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000

In [25]:
df.iat[1,3]

np.int64(60000)

In [27]:
df['Age'] = df['Age'] + 5
df

      Name  Age         City  Salary
0    Alice   42      Charlie   50000
1      Bob   40  Los Angeles   60000
2  Charlie   45      Chicago   70000