In [5]:
import pandas as pd

In [6]:
data = [1,2,3,4,5]
series = pd.Series(data)
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [7]:
data = {"a": 1, "b": 2, "c": 3}
series_dict = pd.Series(data)
series_dict

a    1
b    2
c    3
dtype: int64

In [9]:
dataa = {
    "Name" : ["Alice", "Bob", "Charlie"],
    "Age" : [25, 30, 35],
    "City" : ["New York", "Los Angeles", "Chicago"]
}
df = pd.DataFrame(dataa)
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [10]:
# dataframe from list of dictionaries
dataa = [
    {"Name" : "Alice","Age": 32, "City": "Charlie"},
    {"Name" : "Bob", "Age": 30, "City": "Los Angeles"},
    {"Name" : "Charlie", "Age": 35, "City": "Chicago"}
]

df = pd.DataFrame(dataa)
df

      Name  Age         City
0    Alice   32      Charlie
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [12]:
# Dataframe
data = pd.read_csv('london_weather.csv', sep = ',')
data.head(5)

,Unnamed: 0,Date,Max.TemperatureC,Min.TemperatureC,Max.Gust.SpeedKPH,Events,Season
0,1,1996-06-30,NaN,NaN,NaN,NaN,Summer
1,2,1996-07-01,19.0,11.0,28.0,Rain,Summer
2,3,1996-07-02,20.0,10.0,NaN,NaN,Summer
3,4,1996-07-03,19.0,12.0,NaN,Rain,Summer
4,5,1996-07-04,19.0,12.0,25.0,Rain,Summer

In [29]:
data.iat[1, 1]  # Accessing the first element

'1996-07-01'

In [15]:
# loc is for row index, iloc is for column index
df.loc[0]  # First row
 # First row

Name      Alice
Age          32
City    Charlie
Name: 0, dtype: object

In [18]:
df.loc[0][0]

C:\Users\USER\AppData\Local\Temp\ipykernel_6148\3754930180.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][0]

'Alice'

In [19]:
df

      Name  Age         City
0    Alice   32      Charlie
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [ ]:
df.at[1,'Age'] #getting row index with the colum name

np.int64(30)

In [21]:
df.iat[2,2]

'Chicago'

In [22]:
df['Salary'] = [50000, 60000, 70000]

In [23]:
df

      Name  Age         City  Salary
0    Alice   32      Charlie   50000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000

In [25]:
df.iat[1,3]

np.int64(60000)

In [27]:
df['Age'] = df['Age'] + 5
df

      Name  Age         City  Salary
0    Alice   42      Charlie   50000
1      Bob   40  Los Angeles   60000
2  Charlie   45      Chicago   70000

In [31]:
data.head(5)

,Unnamed: 0,Date,Max.TemperatureC,Min.TemperatureC,Max.Gust.SpeedKPH,Events,Season
0,1,1996-06-30,NaN,NaN,NaN,NaN,Summer
1,2,1996-07-01,19.0,11.0,28.0,Rain,Summer
2,3,1996-07-02,20.0,10.0,NaN,NaN,Summer
3,4,1996-07-03,19.0,12.0,NaN,Rain,Summer
4,5,1996-07-04,19.0,12.0,25.0,Rain,Summer

In [32]:
data.describe()

        Unnamed: 0  Max.TemperatureC  Min.TemperatureC  Max.Gust.SpeedKPH
count  1383.000000       1372.000000       1382.000000         419.000000
mean    693.881417         15.505102          8.151954          32.000000
std     400.505284          6.369429          5.113349           7.174183
min       1.000000         -2.000000         -5.000000          18.000000
25%     347.500000         11.000000          4.000000          28.000000
50%     694.000000         15.000000          9.000000          31.000000
75%    1040.500000         20.000000         12.000000          36.000000
max    1387.000000         33.000000         21.000000          66.000000

In [33]:
data.dtypes

Unnamed: 0             int64
Date                  object
Max.TemperatureC     float64
Min.TemperatureC     float64
Max.Gust.SpeedKPH    float64
Events                object
Season                object
dtype: object

In [ ]:
data.isnull().any() # Check if any null values exist in the DataFrame

Unnamed: 0           False
Date                 False
Max.TemperatureC      True
Min.TemperatureC      True
Max.Gust.SpeedKPH     True
Events                True
Season               False
dtype: bool

In [38]:
data.isnull().sum()  # Count of null values in each column

Unnamed: 0             0
Date                   0
Max.TemperatureC      11
Min.TemperatureC       1
Max.Gust.SpeedKPH    964
Events               461
Season                 0
dtype: int64

In [ ]:
# filling missing values with 0
data_filled = data.fillna(0)  # Fill null values with 0
data_filled.isnull().sum()  # Check again for null values

Unnamed: 0           0
Date                 0
Max.TemperatureC     0
Min.TemperatureC     0
Max.Gust.SpeedKPH    0
Events               0
Season               0
dtype: int64

In [56]:
data_filled_mean = data.fillna(data.select_dtypes(include='number').mean())  # Fill null values with the mean of each column 
data_filled_mean

,Unnamed: 0,Date,Max.TemperatureC,Min.TemperatureC,Max.Gust.SpeedKPH,Events,Season
0,1,1996-06-30,15.505102,8.151954,32.0,NaN,Summer
1,2,1996-07-01,19.000000,11.000000,28.0,Rain,Summer
2,3,1996-07-02,20.000000,10.000000,32.0,NaN,Summer
3,4,1996-07-03,19.000000,12.000000,32.0,Rain,Summer
4,5,1996-07-04,19.000000,12.000000,25.0,Rain,Summer
...,...,...,...,...,...,...,...
1378,1383,2000-06-26,15.505102,13.000000,32.0,Rain,Summer
1379,1384,2000-06-27,22.000000,11.000000,32.0,NaN,Summer
1380,1385,2000-06-28,21.000000,13.000000,32.0,NaN,Summer
1381,1386,2000-06-29,20.000000,14.000000,32.0,Rain-Thunderstorm,Summer
1382,1387,2000-06-30,20.000000,14.000000,32.0,Rain,Summer

In [49]:
data.isnull().sum()

Unnamed: 0             0
Date                   0
Max.TemperatureC      11
Min.TemperatureC       1
Max.Gust.SpeedKPH    964
Events               461
Season                 0
dtype: int64

In [53]:
data_filled

,Unnamed: 0,Date,Max.TemperatureC,Min.TemperatureC,Max.Gust.SpeedKPH,Events,Season
0,1,1996-06-30,0.0,0.0,0.0,0,Summer
1,2,1996-07-01,19.0,11.0,28.0,Rain,Summer
2,3,1996-07-02,20.0,10.0,0.0,0,Summer
3,4,1996-07-03,19.0,12.0,0.0,Rain,Summer
4,5,1996-07-04,19.0,12.0,25.0,Rain,Summer
...,...,...,...,...,...,...,...
1378,1383,2000-06-26,0.0,13.0,0.0,Rain,Summer
1379,1384,2000-06-27,22.0,11.0,0.0,0,Summer
1380,1385,2000-06-28,21.0,13.0,0.0,0,Summer
1381,1386,2000-06-29,20.0,14.0,0.0,Rain-Thunderstorm,Summer
1382,1387,2000-06-30,20.0,14.0,0.0,Rain,Summer

In [58]:
data_filled_mean['Events'].fillna(data_filled_mean['Events'].mode()[0])  # Fill null values with the mode of the 'Events' column

0                    Rain
1                    Rain
2                    Rain
3                    Rain
4                    Rain
              ...
1378                 Rain
1379                 Rain
1380                 Rain
1381    Rain-Thunderstorm
1382                 Rain
Name: Events, Length: 1383, dtype: object

In [60]:
data_filled_mean.head(5)

,Unnamed: 0,Date,Max.TemperatureC,Min.TemperatureC,Max.Gust.SpeedKPH,Events,Season
0,1,1996-06-30,15.505102,8.151954,32.0,Rain,Summer
1,2,1996-07-01,19.000000,11.000000,28.0,Rain,Summer
2,3,1996-07-02,20.000000,10.000000,32.0,Rain,Summer
3,4,1996-07-03,19.000000,12.000000,32.0,Rain,Summer
4,5,1996-07-04,19.000000,12.000000,25.0,Rain,Summer

In [61]:
data_filled_mean = data_filled_mean.rename(columns = {"Date": "Temp Data"})
data_filled_mean.head(5)

,Unnamed: 0,Temp Data,Max.TemperatureC,Min.TemperatureC,Max.Gust.SpeedKPH,Events,Season
0,1,1996-06-30,15.505102,8.151954,32.0,Rain,Summer
1,2,1996-07-01,19.000000,11.000000,28.0,Rain,Summer
2,3,1996-07-02,20.000000,10.000000,32.0,Rain,Summer
3,4,1996-07-03,19.000000,12.000000,32.0,Rain,Summer
4,5,1996-07-04,19.000000,12.000000,25.0,Rain,Summer

In [62]:
grouped_mean = data_filled_mean.groupby('Events')['Max.TemperatureC'].mean()
print(grouped_mean)

Events
Fog                       14.943396
Fog-Rain                  14.032023
Fog-Rain-Snow              7.000000
Fog-Rain-Thunderstorm     17.714286
Fog-Thunderstorm          21.000000
Rain                      15.756785
Rain-Snow                  5.111111
Rain-Snow-Thunderstorm     7.000000
Rain-Thunderstorm         19.390244
Snow                       2.409555
Thunderstorm              23.000000
Name: Max.TemperatureC, dtype: float64

In [63]:
grouped_agg = data_filled_mean.groupby('Events')['Max.TemperatureC'].agg({ 'mean', 'min', 'max', 'std' })
print(grouped_agg)

                         min        max       mean       std
Events
Fog                      2.0  31.000000  14.943396  6.773661
Fog-Rain                 4.0  27.000000  14.032023  5.868518
Fog-Rain-Snow            7.0   7.000000   7.000000       NaN
Fog-Rain-Thunderstorm    9.0  27.000000  17.714286  7.111359
Fog-Thunderstorm        21.0  21.000000  21.000000       NaN
Rain                     1.0  33.000000  15.756785  6.106576
Rain-Snow                1.0   9.000000   5.111111  1.996729
Rain-Snow-Thunderstorm   7.0   7.000000   7.000000       NaN
Rain-Thunderstorm        9.0  28.000000  19.390244  4.716344
Snow                    -2.0  15.505102   2.409555  4.749134
Thunderstorm            23.0  23.000000  23.000000       NaN

In [64]:
# Merging and joining DataFrames

data1 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],    
    'Age': [25, 30, 35]
})
data2 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'David'],    
    'City': ['New York', 'Los Angeles', 'Chicago']
})
data1

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [65]:
data2

    Name         City
0  Alice     New York
1    Bob  Los Angeles
2  David      Chicago

In [66]:
#Merge DataFrames on key column
merged_data = pd.merge(data1, data2, on='Name', how='inner')
merged_data

    Name  Age         City
0  Alice   25     New York
1    Bob   30  Los Angeles

In [67]:
pd.merge(data1, data2, on='Name', how='outer')

      Name   Age         City
0    Alice  25.0     New York
1      Bob  30.0  Los Angeles
2  Charlie  35.0          NaN
3    David   NaN      Chicago

In [68]:
pd.merge(data1, data2, on='Name', how='left')

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35          NaN

In [69]:
pd.merge(data1, data2, on='Name', how='right')

    Name   Age         City
0  Alice  25.0     New York
1    Bob  30.0  Los Angeles
2  David   NaN      Chicago